-- ----------------------------------------
-- ------- Detailed Analytical Plan -------		
-- ----------------------------------------

-- 1. SALES ANALYSIS
-- 	A View/Mart containing information about sales
-- 		Analytical questions: 
-- 			- 1.1 Revenue by Product Category
-- 			- 1.2 Top-Selling Products
-- 			- 1.3 Worst-Selling Products
-- 			- 1.4 Sales Trends Over Time
-- 					just for this I created the view `sales_trends` to show how I would answer these questions
-- --------------------------
-- 2. EMPLOYEE ANALYSIS
-- 	A View/Mart involving data about employees
-- 		Analytical questions:
--  		- 2.1 Top-performing employees
-- 			- 2.2 Employee Performance
-- 			- 2.4 Employee Overload
-- --------------------------
-- 3. CUSTOMER ANALYSIS
-- 	A View/Mart involving data about customers
-- 		Analytical questions:
-- 			- 3.1 Customer Buying Patterns
-- 			- 3.2 Top Customers and their share of revenues
-- 			- 3.3 Who are the contacts?
-- 			- 3.4 Geospatial analysis for countries and cities
-- 			- 3.5 Long-term partnerships/Loyalty analysis
-- --------------------------
-- 4. SHIPPING DESCRIPTIVE ANALYSIS
-- 	 A View/Mart involving data about already shipped orders
-- 		Analytical questions: 
-- 			- 4.1 Efficiency of Shipping Companies
-- 			- 4.2 Shipping Company Performance
-- 			- 4.3 Late Shipments
-- 			- 4.4 Historical Shipping Trends
-- 			- 4.5 Geospatial Analysis
-- -------------------------
-- -------------------------
-- 5. SHIPPING PREDICTIVE ANALYTICS
-- 	A View/Mart involving data about not yet shipped orders
-- 		Analytical questions: 
-- 			- 5.1 Shipments in the Future
-- 			- 5.2 Geospatial Analysis
-- 			- 5.3 Predicted Cost Analysis
-- --------------------------------------------------------------